# Generated by Django 4.1.7 on 2023-04-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('is_trash', models.BooleanField(default=False)),
                ('is_view', models.BooleanField(default=False)),
                ('contacted', models.BooleanField(default=False)),
            ],
        ),
    ]
