# Generated by Django 4.1.7 on 2023-04-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='trash',
            field=models.BooleanField(default=True),
        ),
    ]
