# Generated by Django 4.1.7 on 2023-04-22 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0004_comment_trash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sayt.category'),
        ),
    ]
